# permissions for end users to edit kafkaconsumerperftests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kafka-benchmark-operator
    app.kubernetes.io/managed-by: kustomize
  name: kafkaconsumerperftest-editor-role
rules:
- apiGroups:
  - kafka.platformatory.io
  resources:
  - kafkaconsumerperftests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.platformatory.io
  resources:
  - kafkaconsumerperftests/status
  verbs:
  - get
