apiVersion: kafka.platformatory.io/v1alpha1
kind: KafkaConsumerPerfTest
metadata:
  labels:
    app.kubernetes.io/name: kafka-benchmark-operator
    app.kubernetes.io/managed-by: kustomize
  name: kafkaconsumerperftest-sample
  namespace: demo
spec:
  count: 4
  # image: platformatorylabs/kafka-performance-suite:1.0.1
  bootstrapServers: kafka.confluent.svc.cluster.local:9092
  consumerConfig:
    security.protocol: "PLAINTEXT"
    max.poll.records: "1000"
  # consumerConfigSecretRef:
  #   name: kafka-perf-consumer-config
  consumerPerfParams:
    messagesCount: 100000
    timeout: 100000
  topic:
    name: perf-test
    autoCreate: true
    replicas: 1
    partitions: 1
  metricsCollector:
    provider: prometheus
    jmxPrometheusURLs:
    - kraftcontroller.confluent.svc.cluster.local:7778
    - kafka.confluent.svc.cluster.local:7778
    config:
      remoteWrite:
      - url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
  topologySpreadConstraints:
    - topologyKey: topology.kubernetes.io/zone
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          job: perf-test
      nodeAffinityPolicy: Ignore
      nodeTaintsPolicy: Ignore

