apiVersion: kafka.platformatory.io/v1alpha1
kind: KafkaE2EPerfTest
metadata:
  labels:
    app.kubernetes.io/name: kafka-benchmark-operator
    app.kubernetes.io/managed-by: kustomize
  name: kafkae2eperftest-sample
  namespace: demo
spec:
  count: 1
  image: platformatorylabs/kafka-performance-suite:1.0.1
  bootstrapServers: kafka.confluent.svc.cluster.local:9092
  clientConfig:
    fetch.min.bytes: "5120"
  # clientConfigSecretRef:
  #   name: kafka-perf-e2e-config
  e2ePerfParams:
    recordsCount: 1000
    recordSizeBytes: 5120
    acks: "all"
  topic:
    name: e2e-perf-test-demo
    autoCreate: true
    replicas: 1
    partitions: 1
  metricsCollector:
    provider: prometheus
    jmxPrometheusURLs:
    - kafka.confluent.svc.cluster.local:7778
    config:
      remoteWrite:
      - url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
  topologySpreadConstraints:
    - topologyKey: topology.kubernetes.io/zone
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          job: perf-test
      nodeAffinityPolicy: Ignore
      nodeTaintsPolicy: Ignore
      
